//액션 타입 상수
export default {
	SELECT_BUILD: 'SELECT_BUILD',
	DELETE_BUILD: 'DELETE_BUILD',
	ADD_BUILD: 'ADD_BUILD',
	STOP_BUILD: 'STOP_BUILD',
	START_BUILD: 'START_BUILD',
	ADD_TASKS: 'ADD_TASKS',
	SELECT_TASK: 'SELECT_TASK',
	APPEND_LOG: 'APPEND_LOG'
};
